/**
 * A hand-picked, categorised, keyword-searchable emoji set — not the full
 * Unicode range, but enough to stop `MessageItem.tsx`'s 6-emoji
 * `QUICK_REACTIONS` strip from being the only reactions anyone can ever
 * apply. Hand-rolled rather than a library (e.g. emoji-mart) to match this
 * codebase's dependency discipline and keep the bundle small; swapping in
 * the full set later is a drop-in replacement of this one file.
 */
export type EmojiEntry = { char: string; name: string; keywords: string[] };
export type EmojiCategory = { label: string; emoji: EmojiEntry[] };

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    label: "Smileys",
    emoji: [
      { char: "😀", name: "grinning", keywords: ["happy", "smile"] },
      { char: "😃", name: "smiley", keywords: ["happy", "smile"] },
      { char: "😄", name: "smile", keywords: ["happy", "laugh"] },
      { char: "😁", name: "grin", keywords: ["happy", "smile"] },
      { char: "😆", name: "laughing", keywords: ["happy", "haha"] },
      { char: "😅", name: "sweat smile", keywords: ["laugh", "relief"] },
      { char: "🤣", name: "rofl", keywords: ["laugh", "funny"] },
      { char: "😂", name: "joy", keywords: ["laugh", "cry", "funny"] },
      { char: "🙂", name: "slight smile", keywords: ["happy"] },
      { char: "🙃", name: "upside down", keywords: ["silly", "sarcasm"] },
      { char: "😉", name: "wink", keywords: ["flirt"] },
      { char: "😊", name: "blush", keywords: ["happy", "shy"] },
      { char: "😇", name: "innocent", keywords: ["angel", "halo"] },
      { char: "🥰", name: "smiling with hearts", keywords: ["love", "adore"] },
      { char: "😍", name: "heart eyes", keywords: ["love", "crush"] },
      { char: "🤩", name: "star struck", keywords: ["wow", "excited"] },
      { char: "😘", name: "kiss", keywords: ["love", "flirt"] },
      { char: "😋", name: "yum", keywords: ["tasty", "delicious"] },
      { char: "😜", name: "winking tongue", keywords: ["silly", "playful"] },
      { char: "🤪", name: "zany", keywords: ["crazy", "silly"] },
      { char: "😝", name: "squinting tongue", keywords: ["silly"] },
      { char: "🤑", name: "money mouth", keywords: ["rich", "money"] },
      { char: "🤗", name: "hugging", keywords: ["hug", "warm"] },
      { char: "🤭", name: "hand over mouth", keywords: ["oops", "giggle"] },
      { char: "🤫", name: "shushing", keywords: ["quiet", "secret"] },
      { char: "🤔", name: "thinking", keywords: ["hmm", "consider"] },
      { char: "🫡", name: "saluting", keywords: ["salute", "respect"] },
      { char: "🙄", name: "eye roll", keywords: ["annoyed", "whatever"] },
      { char: "😏", name: "smirk", keywords: ["sly", "smug"] },
      { char: "😒", name: "unamused", keywords: ["meh", "annoyed"] },
      { char: "😬", name: "grimace", keywords: ["awkward", "yikes"] },
      { char: "😌", name: "relieved", keywords: ["calm", "content"] },
      { char: "😔", name: "pensive", keywords: ["sad", "thoughtful"] },
      { char: "😪", name: "sleepy", keywords: ["tired"] },
      { char: "😴", name: "sleeping", keywords: ["zzz", "asleep"] },
      { char: "😷", name: "mask", keywords: ["sick", "ill"] },
      { char: "🤒", name: "thermometer face", keywords: ["sick", "fever"] },
      { char: "🥵", name: "hot face", keywords: ["heat", "sweat"] },
      { char: "🥶", name: "cold face", keywords: ["freezing", "ice"] },
      { char: "😵", name: "dizzy", keywords: ["confused", "knocked out"] },
      { char: "🤯", name: "exploding head", keywords: ["mind blown", "shocked"] },
      { char: "🥳", name: "partying", keywords: ["party", "celebrate"] },
      { char: "😎", name: "cool", keywords: ["sunglasses", "chill"] },
      { char: "🤓", name: "nerd", keywords: ["glasses", "geek"] },
      { char: "😕", name: "confused", keywords: ["unsure"] },
      { char: "😟", name: "worried", keywords: ["concerned"] },
      { char: "🙁", name: "frown", keywords: ["sad"] },
      { char: "😮", name: "open mouth", keywords: ["surprised", "wow"] },
      { char: "😲", name: "astonished", keywords: ["shocked"] },
      { char: "😳", name: "flushed", keywords: ["embarrassed", "blush"] },
      { char: "🥺", name: "pleading", keywords: ["puppy eyes", "please"] },
      { char: "😦", name: "frowning open mouth", keywords: ["shocked"] },
      { char: "😧", name: "anguished", keywords: ["distress"] },
      { char: "😨", name: "fearful", keywords: ["scared"] },
      { char: "😰", name: "anxious", keywords: ["nervous", "sweat"] },
      { char: "😥", name: "sad relieved", keywords: ["disappointed"] },
      { char: "😢", name: "crying", keywords: ["sad", "tear"] },
      { char: "😭", name: "sobbing", keywords: ["cry", "sad"] },
      { char: "😱", name: "screaming", keywords: ["scared", "shock"] },
      { char: "😖", name: "confounded", keywords: ["frustrated"] },
      { char: "😣", name: "persevering", keywords: ["struggling"] },
      { char: "😞", name: "disappointed", keywords: ["sad"] },
      { char: "😓", name: "downcast sweat", keywords: ["tired", "stressed"] },
      { char: "😩", name: "weary", keywords: ["exhausted"] },
      { char: "😫", name: "tired", keywords: ["exhausted"] },
      { char: "🥱", name: "yawning", keywords: ["tired", "bored"] },
      { char: "😤", name: "triumphant", keywords: ["proud", "huff"] },
      { char: "😡", name: "angry", keywords: ["mad", "rage"] },
      { char: "😠", name: "mad", keywords: ["angry"] },
      { char: "🤬", name: "cursing", keywords: ["swearing", "angry"] },
      { char: "😈", name: "smiling devil", keywords: ["evil", "mischief"] },
      { char: "👿", name: "angry devil", keywords: ["evil"] },
      { char: "💀", name: "skull", keywords: ["dead", "lol"] },
      { char: "☠️", name: "skull crossbones", keywords: ["danger", "dead"] },
      { char: "🤡", name: "clown", keywords: ["joke", "silly"] },
      { char: "👻", name: "ghost", keywords: ["spooky", "halloween"] },
      { char: "👽", name: "alien", keywords: ["ufo", "space"] },
      { char: "🤖", name: "robot", keywords: ["bot", "ai"] },
      { char: "😺", name: "smiling cat", keywords: ["cat", "happy"] },
      { char: "😹", name: "crying laughing cat", keywords: ["cat", "funny"] },
    ],
  },
  {
    label: "Gestures & people",
    emoji: [
      { char: "👍", name: "thumbs up", keywords: ["like", "approve", "yes"] },
      { char: "👎", name: "thumbs down", keywords: ["dislike", "no"] },
      { char: "👌", name: "ok hand", keywords: ["okay", "perfect"] },
      { char: "✌️", name: "peace", keywords: ["victory"] },
      { char: "🤞", name: "crossed fingers", keywords: ["luck", "hope"] },
      { char: "🤟", name: "love you", keywords: ["rock", "love"] },
      { char: "🤘", name: "rock on", keywords: ["metal"] },
      { char: "👊", name: "fist bump", keywords: ["punch", "bump"] },
      { char: "✊", name: "raised fist", keywords: ["power", "solidarity"] },
      { char: "👏", name: "clap", keywords: ["applause", "well done"] },
      { char: "🙌", name: "raised hands", keywords: ["celebrate", "praise"] },
      { char: "👐", name: "open hands", keywords: ["hug"] },
      { char: "🤝", name: "handshake", keywords: ["deal", "agreement"] },
      { char: "🙏", name: "folded hands", keywords: ["please", "thanks", "pray"] },
      { char: "💪", name: "flexed biceps", keywords: ["strong", "muscle"] },
      { char: "🫶", name: "heart hands", keywords: ["love", "support"] },
      { char: "👀", name: "eyes", keywords: ["look", "watching"] },
      { char: "🧠", name: "brain", keywords: ["smart", "genius"] },
      { char: "👋", name: "waving hand", keywords: ["hello", "bye"] },
      { char: "🖐️", name: "hand", keywords: ["stop", "high five"] },
      { char: "☝️", name: "index up", keywords: ["point", "one"] },
      { char: "👉", name: "point right", keywords: ["direction"] },
      { char: "👈", name: "point left", keywords: ["direction"] },
      { char: "🤦", name: "facepalm", keywords: ["oops", "smh"] },
      { char: "🤷", name: "shrug", keywords: ["dunno", "idk"] },
      { char: "🕺", name: "dancing", keywords: ["party", "dance"] },
      { char: "💃", name: "dancer", keywords: ["party", "dance"] },
    ],
  },
  {
    label: "Hearts",
    emoji: [
      { char: "❤️", name: "red heart", keywords: ["love"] },
      { char: "🧡", name: "orange heart", keywords: ["love"] },
      { char: "💛", name: "yellow heart", keywords: ["love"] },
      { char: "💚", name: "green heart", keywords: ["love"] },
      { char: "💙", name: "blue heart", keywords: ["love"] },
      { char: "💜", name: "purple heart", keywords: ["love"] },
      { char: "🖤", name: "black heart", keywords: ["love"] },
      { char: "🤍", name: "white heart", keywords: ["love"] },
      { char: "🤎", name: "brown heart", keywords: ["love"] },
      { char: "💔", name: "broken heart", keywords: ["sad", "heartbreak"] },
      { char: "❤️‍🔥", name: "heart on fire", keywords: ["passion"] },
      { char: "💕", name: "two hearts", keywords: ["love"] },
      { char: "💖", name: "sparkling heart", keywords: ["love"] },
      { char: "💗", name: "growing heart", keywords: ["love"] },
      { char: "💘", name: "heart with arrow", keywords: ["cupid", "love"] },
      { char: "💝", name: "heart with ribbon", keywords: ["gift", "love"] },
      { char: "💞", name: "revolving hearts", keywords: ["love"] },
    ],
  },
  {
    label: "Celebration",
    emoji: [
      { char: "🎉", name: "party popper", keywords: ["celebrate", "congrats"] },
      { char: "🎊", name: "confetti ball", keywords: ["celebrate", "party"] },
      { char: "🎈", name: "balloon", keywords: ["party", "birthday"] },
      { char: "🎂", name: "birthday cake", keywords: ["birthday", "cake"] },
      { char: "🥂", name: "clinking glasses", keywords: ["cheers", "toast"] },
      { char: "🍾", name: "champagne", keywords: ["celebrate", "party"] },
      { char: "🏆", name: "trophy", keywords: ["win", "award"] },
      { char: "🥇", name: "gold medal", keywords: ["first", "win"] },
      { char: "🔥", name: "fire", keywords: ["lit", "hot", "great"] },
      { char: "✨", name: "sparkles", keywords: ["shine", "magic"] },
      { char: "⭐", name: "star", keywords: ["favorite"] },
      { char: "🌟", name: "glowing star", keywords: ["shine"] },
      { char: "💯", name: "hundred", keywords: ["perfect", "100"] },
      { char: "✅", name: "check mark", keywords: ["done", "yes", "approved"] },
      { char: "❌", name: "cross mark", keywords: ["no", "wrong"] },
      { char: "⚡", name: "lightning", keywords: ["fast", "energy"] },
      { char: "💥", name: "collision", keywords: ["boom", "impact"] },
      { char: "🎯", name: "bullseye", keywords: ["target", "on point"] },
      { char: "🚀", name: "rocket", keywords: ["launch", "fast", "ship"] },
      { char: "🎁", name: "gift", keywords: ["present"] },
    ],
  },
  {
    label: "Objects & symbols",
    emoji: [
      { char: "💡", name: "light bulb", keywords: ["idea"] },
      { char: "💬", name: "speech bubble", keywords: ["chat", "talk"] },
      { char: "💭", name: "thought bubble", keywords: ["think"] },
      { char: "📌", name: "pushpin", keywords: ["pin", "important"] },
      { char: "📎", name: "paperclip", keywords: ["attach", "file"] },
      { char: "📝", name: "memo", keywords: ["note", "write"] },
      { char: "📅", name: "calendar", keywords: ["date", "schedule"] },
      { char: "⏰", name: "alarm clock", keywords: ["time", "reminder"] },
      { char: "⏳", name: "hourglass", keywords: ["waiting", "time"] },
      { char: "🔒", name: "locked", keywords: ["private", "secure"] },
      { char: "🔓", name: "unlocked", keywords: ["open"] },
      { char: "🔑", name: "key", keywords: ["access", "unlock"] },
      { char: "🔍", name: "magnifying glass", keywords: ["search", "find"] },
      { char: "☕", name: "coffee", keywords: ["drink", "break"] },
      { char: "🍕", name: "pizza", keywords: ["food"] },
      { char: "🍺", name: "beer", keywords: ["drink", "cheers"] },
      { char: "🐛", name: "bug", keywords: ["error", "issue"] },
      { char: "🚧", name: "construction", keywords: ["wip", "in progress"] },
      { char: "🛑", name: "stop sign", keywords: ["stop", "halt"] },
      { char: "❓", name: "question mark", keywords: ["confused", "ask"] },
      { char: "❗", name: "exclamation", keywords: ["important", "alert"] },
      { char: "♻️", name: "recycle", keywords: ["reuse"] },
      { char: "🌈", name: "rainbow", keywords: ["pride", "colorful"] },
      { char: "☀️", name: "sun", keywords: ["sunny", "weather"] },
      { char: "🌧️", name: "rain", keywords: ["weather"] },
    ],
  },
];
